/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        background: '#121318',
        'on-background': '#e3e1e9',
        surface: '#121318',
        'surface-dim': '#121318',
        'surface-bright': '#38393f',
        'surface-container-lowest': '#0d0e13',
        'surface-container-low': '#1a1b21',
        'surface-container': '#1e1f25',
        'surface-container-high': '#292a2f',
        'surface-container-highest': '#34343a',
        'surface-variant': '#34343a',
        'on-surface': '#e3e1e9',
        'on-surface-variant': '#c7c4d7',
        'inverse-surface': '#e3e1e9',
        'inverse-on-surface': '#2f3036',
        outline: '#908fa0',
        'outline-variant': '#464554',
        'surface-tint': '#c0c1ff',
        primary: {
          DEFAULT: '#c0c1ff',
          foreground: '#1000a9',
          container: '#8083ff',
        },
        'on-primary': '#1000a9',
        'primary-container': '#8083ff',
        'on-primary-container': '#0d0096',
        'inverse-primary': '#494bd6',
        secondary: {
          DEFAULT: '#bdc2ff',
          foreground: '#131e8c',
          container: '#2f3aa3',
        },
        'on-secondary': '#131e8c',
        'secondary-container': '#2f3aa3',
        'on-secondary-container': '#a8afff',
        'secondary-fixed': '#e0e0ff',
        'secondary-fixed-dim': '#bdc2ff',
        tertiary: {
          DEFAULT: '#4edea3',
          foreground: '#003824',
          container: '#00885d',
        },
        'on-tertiary': '#003824',
        'tertiary-container': '#00885d',
        'on-tertiary-container': '#000703',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        error: {
          DEFAULT: '#ffb4ab',
          foreground: '#690005',
          container: '#93000a',
        },
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        // Compatibility tokens
        text: {
          primary: '#e3e1e9',
          secondary: '#c7c4d7',
          muted: '#908fa0',
        },
        status: {
          success: '#4edea3',
          warning: '#fbbf24',
          danger: '#ffb4ab',
          info: '#bdc2ff',
        },
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Plus Jakarta Sans', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
