/**
 * SMCore Global Enums
 */

export enum StaffPermission {
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_AUDIT_LOG = 'VIEW_AUDIT_LOG',
  MANAGE_MODERATION = 'MANAGE_MODERATION',
  MANAGE_AUTOMOD = 'MANAGE_AUTOMOD',
  MANAGE_TICKETS = 'MANAGE_TICKETS',
  MANAGE_GUILD_SETTINGS = 'MANAGE_GUILD_SETTINGS',
  FULL_ADMIN = 'FULL_ADMIN',
}

export enum ModerationAction {
  BAN = 'BAN',
  UNBAN = 'UNBAN',
  KICK = 'KICK',
  TIMEOUT = 'TIMEOUT',
  UNTIMEOUT = 'UNTIMEOUT',
  WARN = 'WARN',
  PURGE = 'PURGE',
  LOCK = 'LOCK',
  UNLOCK = 'UNLOCK',
  SLOWMODE = 'SLOWMODE',
  NICKNAME = 'NICKNAME',
  SOFTBAN = 'SOFTBAN',
}

export enum CaseStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
}

export enum WarningStatus {
  ACTIVE = 'ACTIVE',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
}

export enum HierarchyCheckResult {
  SUCCESS = 'SUCCESS',
  TARGET_IS_GUILD_OWNER = 'TARGET_IS_GUILD_OWNER',
  TARGET_ROLE_TOO_HIGH = 'TARGET_ROLE_TOO_HIGH',
  BOT_ROLE_TOO_LOW = 'BOT_ROLE_TOO_LOW',
  TARGET_IS_BOT = 'TARGET_IS_BOT',
  TARGET_IS_SELF = 'TARGET_IS_SELF',
  PROTECTED_TARGET = 'PROTECTED_TARGET',
}

export enum ProtectionType {
  SPAM = 'SPAM',
  MASS_MENTION = 'MASS_MENTION',
  DISCORD_INVITE = 'DISCORD_INVITE',
  EXTERNAL_LINK = 'EXTERNAL_LINK',
  PROHIBITED_KEYWORD = 'PROHIBITED_KEYWORD',
}

export enum AutoModPunishment {
  DELETE = 'DELETE',
  WARN = 'WARN',
  TIMEOUT = 'TIMEOUT',
  KICK = 'KICK',
  BAN = 'BAN',
}

export enum AutoModTrigger {
  SPAM = 'SPAM',
  MASS_MENTION = 'MASS_MENTION',
  INVITES = 'INVITES',
  LINKS = 'LINKS',
  BAD_WORDS = 'BAD_WORDS',
  ATTACHMENTS = 'ATTACHMENTS',
}

export enum AutoModAction {
  DELETE_MESSAGE = 'DELETE_MESSAGE',
  WARN_USER = 'WARN_USER',
  TIMEOUT_USER = 'TIMEOUT_USER',
  ALERT_STAFF = 'ALERT_STAFF',
}

export enum LogCategory {
  MODERATION = 'MODERATION',
  MEMBERS = 'MEMBERS',
  MESSAGES = 'MESSAGES',
  ROLES = 'ROLES',
  CHANNELS = 'CHANNELS',
  AUTOMOD = 'AUTOMOD',
  SYSTEM = 'SYSTEM',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  CLAIMED = 'CLAIMED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}
