/**
 * SMCore Global Enums
 */

export enum StaffPermission {
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  VIEW_AUDIT_LOG = 'VIEW_AUDIT_LOG',
  MANAGE_MODERATION = 'MANAGE_MODERATION',
  MANAGE_AUTOMOD = 'MANAGE_AUTOMOD',
  MANAGE_TICKETS = 'MANAGE_TICKETS',
  MANAGE_GUILD_SETTINGS = 'MANAGE_GUILD_SETTINGS',
  FULL_ADMIN = 'FULL_ADMIN',
}

export enum ModerationAction {
  BAN = 'BAN',
  UNBAN = 'UNBAN',
  KICK = 'KICK',
  TIMEOUT = 'TIMEOUT',
  UNTIMEOUT = 'UNTIMEOUT',
  WARN = 'WARN',
  PURGE = 'PURGE',
  LOCK = 'LOCK',
  UNLOCK = 'UNLOCK',
  SLOWMODE = 'SLOWMODE',
  NICKNAME = 'NICKNAME',
  SOFTBAN = 'SOFTBAN',
}

export enum CaseStatus {
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
}

export enum WarningStatus {
  ACTIVE = 'ACTIVE',
  REVOKED = 'REVOKED',
  EXPIRED = 'EXPIRED',
}

export enum HierarchyCheckResult {
  SUCCESS = 'SUCCESS',
  TARGET_IS_GUILD_OWNER = 'TARGET_IS_GUILD_OWNER',
  TARGET_ROLE_TOO_HIGH = 'TARGET_ROLE_TOO_HIGH',
  BOT_ROLE_TOO_LOW = 'BOT_ROLE_TOO_LOW',
  TARGET_IS_BOT = 'TARGET_IS_BOT',
  TARGET_IS_SELF = 'TARGET_IS_SELF',
  PROTECTED_TARGET = 'PROTECTED_TARGET',
}

export enum ProtectionType {
  SPAM = 'SPAM',
  MASS_MENTION = 'MASS_MENTION',
  DISCORD_INVITE = 'DISCORD_INVITE',
  EXTERNAL_LINK = 'EXTERNAL_LINK',
  PROHIBITED_KEYWORD = 'PROHIBITED_KEYWORD',
}

export enum AutoModPunishment {
  DELETE = 'DELETE',
  WARN = 'WARN',
  TIMEOUT = 'TIMEOUT',
  KICK = 'KICK',
  BAN = 'BAN',
}

export enum SecurityRiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum SecurityAction {
  NONE = 'NONE',
  QUARANTINE = 'QUARANTINE',
  WARN = 'WARN',
  TIMEOUT = 'TIMEOUT',
  KICK = 'KICK',
  BAN = 'BAN',
}

export enum SecurityEventType {
  SUSPICIOUS_JOIN = 'SUSPICIOUS_JOIN',
  ACCOUNT_TOO_YOUNG = 'ACCOUNT_TOO_YOUNG',
  RAID_DETECTED = 'RAID_DETECTED',
  RAID_MODE_STARTED = 'RAID_MODE_STARTED',
  RAID_MODE_ENDED = 'RAID_MODE_ENDED',
  QUARANTINED_MEMBER = 'QUARANTINED_MEMBER',
  RELEASED_MEMBER = 'RELEASED_MEMBER',
  SECURITY_ACTION_FAILED = 'SECURITY_ACTION_FAILED',
}

export enum AutoModTrigger {
  SPAM = 'SPAM',
  MASS_MENTION = 'MASS_MENTION',
  INVITES = 'INVITES',
  LINKS = 'LINKS',
  BAD_WORDS = 'BAD_WORDS',
  ATTACHMENTS = 'ATTACHMENTS',
}

export enum AutoModAction {
  DELETE_MESSAGE = 'DELETE_MESSAGE',
  WARN_USER = 'WARN_USER',
  TIMEOUT_USER = 'TIMEOUT_USER',
  ALERT_STAFF = 'ALERT_STAFF',
}

export enum LogCategory {
  MODERATION = 'MODERATION',
  MEMBERS = 'MEMBERS',
  MESSAGES = 'MESSAGES',
  ROLES = 'ROLES',
  CHANNELS = 'CHANNELS',
  AUTOMOD = 'AUTOMOD',
  SYSTEM = 'SYSTEM',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  CLAIMED = 'CLAIMED',
  CLOSED = 'CLOSED',
  REOPENED = 'REOPENED',
  RESOLVED = 'RESOLVED',
}

export enum TicketAction {
  CREATE = 'CREATE',
  CLAIM = 'CLAIM',
  UNCLAIM = 'UNCLAIM',
  CLOSE = 'CLOSE',
  REOPEN = 'REOPEN',
  DELETE = 'DELETE',
  TRANSCRIPT = 'TRANSCRIPT',
}

export enum AuditEventType {
  MODERATION_ACTION = 'MODERATION_ACTION',
  WARNING_CREATED = 'WARNING_CREATED',
  WARNING_REVOKED = 'WARNING_REVOKED',
  CASE_CREATED = 'CASE_CREATED',
  NOTE_CREATED = 'NOTE_CREATED',
  NOTE_REVOKED = 'NOTE_REVOKED',
  MESSAGE_DELETED = 'MESSAGE_DELETED',
  CHANNEL_LOCKED = 'CHANNEL_LOCKED',
  CHANNEL_UNLOCKED = 'CHANNEL_UNLOCKED',
  SLOWMODE_CHANGED = 'SLOWMODE_CHANGED',
  NICKNAME_CHANGED = 'NICKNAME_CHANGED',

  AUTOMOD_TRIGGERED = 'AUTOMOD_TRIGGERED',
  SPAM_DETECTED = 'SPAM_DETECTED',
  MASS_MENTION_DETECTED = 'MASS_MENTION_DETECTED',
  DISCORD_INVITE_DETECTED = 'DISCORD_INVITE_DETECTED',
  EXTERNAL_LINK_DETECTED = 'EXTERNAL_LINK_DETECTED',
  PROHIBITED_KEYWORD_DETECTED = 'PROHIBITED_KEYWORD_DETECTED',

  SECURITY_EVENT = 'SECURITY_EVENT',
  SUSPICIOUS_JOIN = 'SUSPICIOUS_JOIN',
  ACCOUNT_TOO_YOUNG = 'ACCOUNT_TOO_YOUNG',
  RAID_DETECTED = 'RAID_DETECTED',
  RAID_MODE_STARTED = 'RAID_MODE_STARTED',
  RAID_MODE_ENDED = 'RAID_MODE_ENDED',
  MEMBER_QUARANTINED = 'MEMBER_QUARANTINED',
  MEMBER_RELEASED = 'MEMBER_RELEASED',
  SECURITY_ACTION_FAILED = 'SECURITY_ACTION_FAILED',

  TICKET_EVENT = 'TICKET_EVENT',
  TICKET_CREATED = 'TICKET_CREATED',
  TICKET_CLAIMED = 'TICKET_CLAIMED',
  TICKET_UNCLAIMED = 'TICKET_UNCLAIMED',
  TICKET_USER_ADDED = 'TICKET_USER_ADDED',
  TICKET_USER_REMOVED = 'TICKET_USER_REMOVED',
  TICKET_RENAMED = 'TICKET_RENAMED',
  TICKET_CLOSED = 'TICKET_CLOSED',
  TICKET_REOPENED = 'TICKET_REOPENED',
  TICKET_DELETED = 'TICKET_DELETED',
  TICKET_TRANSCRIPT_GENERATED = 'TICKET_TRANSCRIPT_GENERATED',

  CONFIGURATION_CHANGED = 'CONFIGURATION_CHANGED',
  SYSTEM_EVENT = 'SYSTEM_EVENT',
  BOT_ERROR = 'BOT_ERROR',
}

export enum AuditAction {
  BAN = 'BAN',
  UNBAN = 'UNBAN',
  KICK = 'KICK',
  TIMEOUT = 'TIMEOUT',
  UNTIMEOUT = 'UNTIMEOUT',
  WARN = 'WARN',
  REMOVE_WARNING = 'REMOVE_WARNING',
  CLEAR_WARNINGS = 'CLEAR_WARNINGS',
  NOTE = 'NOTE',
  PURGE = 'PURGE',
  LOCK = 'LOCK',
  UNLOCK = 'UNLOCK',
  SLOWMODE = 'SLOWMODE',
  NICKNAME = 'NICKNAME',

  DELETE_MESSAGE = 'DELETE_MESSAGE',
  QUARANTINE = 'QUARANTINE',
  RELEASE = 'RELEASE',
  RAID_MODE_ENABLE = 'RAID_MODE_ENABLE',
  RAID_MODE_DISABLE = 'RAID_MODE_DISABLE',

  TICKET_CREATE = 'TICKET_CREATE',
  TICKET_CLAIM = 'TICKET_CLAIM',
  TICKET_UNCLAIM = 'TICKET_UNCLAIM',
  TICKET_ADD_USER = 'TICKET_ADD_USER',
  TICKET_REMOVE_USER = 'TICKET_REMOVE_USER',
  TICKET_RENAME = 'TICKET_RENAME',
  TICKET_CLOSE = 'TICKET_CLOSE',
  TICKET_REOPEN = 'TICKET_REOPEN',
  TICKET_DELETE = 'TICKET_DELETE',
  TICKET_TRANSCRIPT = 'TICKET_TRANSCRIPT',

  CONFIG_UPDATE = 'CONFIG_UPDATE',
  SYSTEM = 'SYSTEM',
}

export enum AuditTargetType {
  USER = 'USER',
  CHANNEL = 'CHANNEL',
  ROLE = 'ROLE',
  GUILD = 'GUILD',
  MESSAGE = 'MESSAGE',
  TICKET = 'TICKET',
}

